New mqtt library
wirenboard/wb-mqtt-zway-plugin pull request #4
Opened 2022-11-14 07:57 UTC by ekateluv

Сделала использование библиотеки mqtt от z-wave, удалила папку с нашей библиотекой, подняла версию, убрала из настроек модуля параметры, которые в коде не использовались.

2022-11-14 10:33 UTC, KraPete commented on index.js
> +		self.client = new mqtt(self.config.host, parseInt(self.config.port), self.config.clientId);
Раз скобочки начала ставить, то уж и тут поставь :)

2022-11-21 05:33 UTC, webconn requested changes

2022-11-21 05:33 UTC, webconn commented on index.js
> +	if (self.config.user != "none" && self.config.password != "none") {
А там правда вылетает строка `"none"`, если не настроено? То есть, я не смогу подключиться к брокеру с логином или паролем `"none"`?

Я понимаю, что это из старого кода, но всё же

2022-11-21 05:33 UTC, webconn commented on index.js
> +	self.controller.devices.on('removed', self.removeСallback);
Это специально сюда переехало из `onConnect`?

2022-11-21 05:33 UTC, webconn commented on index.js
> +	//var topic = topic.toString();
Лишние комментарии?

2022-11-21 07:29 UTC, ekateluv commented on index.js
> +	if (self.config.user != "none" && self.config.password != "none") {
Там у них к сожалению так работает сервер, я не могу присвоить параметру начение пустая строка. Даже если я зайду в настройки плагина, сотру оттуда "none" из полей логина/пароля, нажму сохранить, а потом снова зайду в настройки, там снова будет none. Потому что сервер посчитает пустую строку некорректной и не сохранит новое значение.
Я писала об этом коллегам из zwave, они написали что так быть не должно. Тем временем 4.0.0 вышел, а баг остался(

2022-11-22 16:46 UTC, PoltoS requested changes

2022-11-22 16:46 UTC, PoltoS commented on module.json
>  		"source": "https://github.com/Edubits/Zway-MQTT",
Better use here https://github.com/wirenboard/wb-mqtt-zway-plugin

2022-11-22 16:46 UTC, PoltoS commented on module.json
>  		"user": "none",
This line is the reason for "none" in empty user and password fields

2022-11-22 16:46 UTC, PoltoS commented on module.json
>  		"user": "none",
remove this line not to have default value (or change to "")

2022-11-22 16:46 UTC, PoltoS commented on index.js
> +	if (self.config.user != "none" && self.config.password != "none") {
This can be fixed by editing modules.json (defaults section)

2022-11-22 16:46 UTC, PoltoS commented on index.js
> +	else{
This can be done in one line. Passing "" as user and password means no authentication.

2022-12-15 10:40 UTC, webconn reviewed
Тут же по старым замечаниям ничего не сделано

2022-12-15 15:39 UTC, ekateluv commented
@webconn а что конкретно не исправлено? логику про подключения я исправила. Причины оставить none я тебе рассказала, ты согласился, а больше тут ничего и нет, вроде. Ридми сейчас еще поправлю только.

2022-12-15 19:18 UTC, PoltoS commented
А мои комменты посмотрели?

2022-12-16 07:09 UTC, ekateluv commented
@PoltoS Да, посмотрели. Смотрите, убрать дефолтные настройки мы можем, тогда там по умолчанию будет пустая строка и клиент будет подключаться без логина и пароля. Но если вдруг пользователь захочет сделать подключение с логином/паролем, впишет туда что то. сохранит, а потом передумает и снова захочет сделать подключение без логина/пароля, то он уже не сможет сохранить пустые строки в этих настройках, сервер не даст. А код то уже только пустые строки признает. Единственным выходом будет сносить приложение и снова устанавливать. Меня пока вот эта ситуация останавливает

2022-12-17 02:33 UTC, PoltoS commented
Ясно. Это баг интерфейса. Можем изучить и поправить. Но можем пока всё оставить как есть

2022-12-20 10:04 UTC, ekateluv commented
Решили влить обновления пока так. Если баг интерфейса будет поправлен, то внесем изменения отдельным пр.

2022-12-20 10:18 UTC, webconn approved these changes

2022-12-20 10:25 UTC, merged